# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v9TeHOkp5tuGvZ1LON2moI09PcrB1jHh
"""

import streamlit as st
import gspread
import pandas as pd
from google.oauth2.service_account import Credentials
import json

# --- إعداد الصفحة ---
st.set_page_config(page_title="منظومة عائلة فطيس", page_icon="🌳", layout="centered")

# --- دالة الاتصال الآمنة (تقرأ من الـ Secrets) ---
def get_connection():
    # هذا الكود يقرأ الإعدادات من خزنة Streamlit بأمان
    creds_dict = json.loads(st.secrets["GOOGLE_CREDS"])
    creds = Credentials.from_service_account_info(
        creds_dict,
        scopes=["https://spreadsheets.google.com/feeds", "https://www.googleapis.com/auth/drive"]
    )
    client = gspread.authorize(creds)
    # استبدل باسم الشيت الخاص بك
    return client.open("منظومة عائلة فطيس").sheet1

# --- الواجهة ---
st.title("🌳 منظومة عائلة فطيس")

# زر تجريبي
if st.button("تحميل البيانات"):
    try:
        sheet = get_connection()
        data = sheet.get_all_records()
        df = pd.DataFrame(data)
        st.write("تم تحميل البيانات بنجاح:")
        st.dataframe(df)
    except Exception as e:
        st.error(f"خطأ في الاتصال: {e}")